version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: library-db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 33061:3306
    networks:
      - librarian
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-be
    user: "${UID}:${GID}"
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - librarian
    volumes:
      - ./:/app/backend
      - /app/backend/node_modules
    depends_on:
      - db
    expose:
      - 8000

networks:
  librarian:
    driver: bridge

volumes:
  db-data:
    driver: local
